pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package -Denforcer.skip=true'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.skip=true'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete') {
            steps {
                echo "Everything is DONE!"
            }
        }
        stage('Extra') {
            steps {
                echo "Hello World, this is my first branch"
            }
        }
    }
}
